// <auto-generated />
using System;
using FreshMarket.ProductService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshMarket.ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260218070230_UpdateProductNameMaxLength")]
    partial class UpdateProductNameMaxLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreshMarket.ProductService.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Products_Category");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("IX_Products_IsAvailable");

                    b.HasIndex("Category", "IsAvailable")
                        .HasDatabaseName("IX_Products_Category_IsAvailable");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Frutas",
                            CreatedAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manzanas rojas frescas de la mejor calidad",
                            ImageUrl = "https://example.com/images/manzana-roja.jpg",
                            IsAvailable = true,
                            Name = "Manzana Roja",
                            Price = 2.50m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Category = "Verduras",
                            CreatedAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lechuga fresca cultivada orgánicamente",
                            ImageUrl = "https://example.com/images/lechuga.jpg",
                            IsAvailable = true,
                            Name = "Lechuga Orgánica",
                            Price = 1.80m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "Lácteos",
                            CreatedAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Leche entera pasteurizada 1L",
                            ImageUrl = "https://example.com/images/leche.jpg",
                            IsAvailable = true,
                            Name = "Leche Entera",
                            Price = 3.20m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 4,
                            Category = "Panadería",
                            CreatedAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pan integral recién horneado",
                            ImageUrl = "https://example.com/images/pan-integral.jpg",
                            IsAvailable = true,
                            Name = "Pan Integral",
                            Price = 2.00m,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
