// <auto-generated />
using System;
using FreshMarket.OrderService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshMarket.OrderService.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260301161237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreshMarket.OrderService.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único del item en el carrito");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha de creación del item");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("ID del producto (referencia a ProductService)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Cantidad de unidades del producto");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha de última actualización");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("ID del usuario (referencia a UserService)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CartItems_UserId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_CartItems_UserId_ProductId");

                    b.ToTable("CartItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CartItems_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("FreshMarket.OrderService.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único del pedido (auto-incremental)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha y hora de creación del pedido (UTC)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Identificador del producto en el pedido (int, referencia a ProductService)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Cantidad de productos en el pedido");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Precio total del pedido (Quantity * UnitPrice)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Precio unitario del producto al momento de la compra");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("Identificador del usuario que realiza el pedido (int, referencia a UserService)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Orders_CreatedAt");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Orders_ProductId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Orders_UserId");

                    b.HasIndex("ProductId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Orders_ProductId_CreatedAt");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Orders_UserId_CreatedAt");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_Orders_TotalPrice_NonNegative", "[TotalPrice] >= 0");

                            t.HasCheckConstraint("CK_Orders_UnitPrice_NonNegative", "[UnitPrice] >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
